#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//1 = forward
//2 = left
//3 = backwards
//4 = right
int power = 50;

void move(int dir, float seconds)
{
	if(dir == 1)
	{
		motor[leftwheel] = power;
		motor[rightwheel] = power;

		wait10Msec(seconds * 100);

		motor[leftwheel] = 0;
		motor[rightwheel] = 0;
	}
	if(dir == 2)
	{
		motor[leftwheel] = -power;
		motor[rightwheel] = power;

		wait10Msec(seconds * 100);

		motor[leftwheel] = 0;
		motor[rightwheel] = 0;
	}

	if(dir == 3)
	{
		motor[leftwheel] = -power;
		motor[rightwheel] = -power;

		wait10Msec(seconds * 100);

		motor[leftwheel] = 0;
		motor[rightwheel] = 0;
	}

	if(dir == 4)
	{
		motor[leftwheel] = power;
		motor[rightwheel] = -power;

		wait10Msec(seconds * 100);

		motor[leftwheel] = 0;
		motor[rightwheel] = 0;
	}

}
//1 = forward
//2 = left
//3 = backward
//4 = right

task main()
{
	waitForStart();
	move(1, 1);
	move(2, 0.2);
	move(1, 1.3);


}
