#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	getJoystickSettings(joystick);
int threshold = 10;
	while(true)
	{
		//josytick 1
	    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[leftwheel] = joystick.joy1_y1; //y2 controller moves motorE
    }
    else
    {
      motor[leftwheel] = 0;
    }
    		//josytick 1
	    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[rightwheel] = joystick.joy1_y2; //y2 controller moves motorE
    }
    else
    {
      motor[rightwheel] = 0;
    }
	  //Flag Spinner
	    if(abs(joystick.joy2_y1) > threshold)
    {
      motor[flag] = joystick.joy2_y1; //y2 controller moves motorE
    }
    else
    {
      motor[flag] = 0;
    }
}
}
